# Generated by Django 5.2.1 on 2025-06-03 22:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('telefone', models.CharField(blank=True, max_length=255, null=True)),
                ('grupo', models.CharField(choices=[('grupo_a', '0 a 9 anos'), ('grupo_b', '10 a 12 anos'), ('grupo_c', '13 anos ou mais')], max_length=255)),
                ('idade', models.IntegerField()),
                ('data_inscricao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('quitado', 'Quitado')], max_length=255)),
                ('valor_pagar', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('criador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inscrição',
                'verbose_name_plural': 'Inscrições',
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('data_pagamento', models.DateTimeField(auto_now_add=True)),
                ('metodo_pagamento', models.CharField(choices=[('pix', 'Pix'), ('dinheiro', 'Dinheiro'), ('cartao', 'Cartão')], max_length=255)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.inscricao')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
            },
        ),
    ]
